# Generated by Django 4.2.6 on 2023-10-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_therapist',
            field=models.BooleanField(default=False),
        ),
    ]
