# Generated by Django 4.2.6 on 2023-10-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='Session', max_length=40),
            preserve_default=False,
        ),
    ]
